name: run main.py

on:
  schedule:
    - cron: '*/5 * * * *' # Cada 5 minutos

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # Lleva el contenido del repositorio al github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # instala la version de pyhon necesaria
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # Ejecuta main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py